export default [
  {
    "_id": "Q1", // string
    "title": "Title 1 :)",
    "course": "RS101",
    "quiz type": "Graded Quiz",
    "points": 50,
    "number of questions": 10,
    "assignment group": "Quizzes",
    "shuffle answers": "Yes",
    "time limit": "20 Minutes",
    "multiple attempts": "No",
    "how many attempts": 1,
    "show correct answers": "After Due Date",
    "access code": "",
    "one question at a time": "Yes",
    "webcam required": "No",
    "lock questions after answering": "No",
    "due date": "2025-04-10",
    "available date": "2025-04-01",
    "until date": "2025-04-11"
  },
  {
    "_id": "2",
    "title": "Title 2 :-)",
    "course": "RS102",
    "quiz type": "Practice Quiz",
    "points": 30,
    "number of questions": 6,
    "assignment group": "Exams",
    "shuffle answers": "No",
    "time limit": "30 Minutes",
    "multiple attempts": "Yes",
    "how many attempts": 3,
    "show correct answers": "Immediately",
    "access code": "QUIZ123",
    "one question at a time": "No",
    "webcam required": "No",
    "lock questions after answering": "No",
    "due date": "2025-04-15",
    "available date": "2025-04-10",
    "until date": "2025-04-16"
  },
  {
    "_id": "3",
    "course": "RS101",
    "title": "Title 3 :3",
    "quiz type": "Graded Survey",
    "points": 10,
    "number of questions": 5,
    "assignment group": "Assignments",
    "shuffle answers": "Yes",
    "time limit": "20 Minutes",
    "multiple attempts": "No",
    "how many attempts": 1,
    "show correct answers": "Never",
    "access code": "SURVEY2025",
    "one question at a time": "Yes",
    "webcam required": "No",
    "lock questions after answering": "Yes",
    "due date": "2025-04-20",
    "available date": "2025-04-18",
    "until date": "2025-04-21"
  },
  {
    "_id": "4",
    "title": "Title 4 :)",
    "course": "RS102",
    "quiz type": "Ungraded Survey",
    "points": 0,
    "number of questions": 8,
    "assignment group": "Project",
    "shuffle answers": "No",
    "time limit": "No Limit",
    "multiple attempts": "Yes",
    "how many attempts": 5,
    "show correct answers": "Always",
    "access code": "",
    "one question at a time": "No",
    "webcam required": "No",
    "lock questions after answering": "No",
    "due date": "2025-04-25",
    "available date": "2025-04-20",
    "until date": "2025-04-26"
  },
  {
    "_id": "5",
    "title": "Title 5 :D",
    "course": "RS101",
    "quiz type": "Graded Quiz",
    "points": 100,
    "number of questions": 20,
    "assignment group": "Exams",
    "shuffle answers": "Yes",
    "time limit": "45 Minutes",
    "multiple attempts": "No",
    "how many attempts": 1,
    "show correct answers": "After Until Date",
    "access code": "FINAL2025",
    "one question at a time": "Yes",
    "webcam required": "Yes",
    "lock questions after answering": "Yes",
    "due date": "2025-05-05",
    "available date": "2025-05-01",
    "until date": "2025-05-06"
  }
];
