export default [
    {
      "Quiz Type": "Graded Quiz",
      "Points": 50,
      "Number of Questions": 10,
      "Assignment Group": "Quizzes",
      "Shuffle Answers": "Yes",
      "Time Limit": "20 Minutes",
      "Multiple Attempts": "No",
      "How Many Attempts": 1,
      "Show Correct Answers": "After Due Date",
      "Access Code": "",
      "One Question at a Time": "Yes",
      "Webcam Required": "No",
      "Lock Questions After Answering": "No",
      "Due Date": "2025-04-10",
      "Available Date": "2025-04-01",
      "Until Date": "2025-04-11"
    },
    {
      "Quiz Type": "Practice Quiz",
      "Points": 30,
      "Number of Questions": 6,
      "Assignment Group": "Exams",
      "Shuffle Answers": "No",
      "Time Limit": "30 Minutes",
      "Multiple Attempts": "Yes",
      "How Many Attempts": 3,
      "Show Correct Answers": "Immediately",
      "Access Code": "QUIZ123",
      "One Question at a Time": "No",
      "Webcam Required": "No",
      "Lock Questions After Answering": "No",
      "Due Date": "2025-04-15",
      "Available Date": "2025-04-10",
      "Until Date": "2025-04-16"
    },
    {
      "Quiz Type": "Graded Survey",
      "Points": 10,
      "Number of Questions": 5,
      "Assignment Group": "Assignments",
      "Shuffle Answers": "Yes",
      "Time Limit": "20 Minutes",
      "Multiple Attempts": "No",
      "How Many Attempts": 1,
      "Show Correct Answers": "Never",
      "Access Code": "SURVEY2025",
      "One Question at a Time": "Yes",
      "Webcam Required": "No",
      "Lock Questions After Answering": "Yes",
      "Due Date": "2025-04-20",
      "Available Date": "2025-04-18",
      "Until Date": "2025-04-21"
    },
    {
      "Quiz Type": "Ungraded Survey",
      "Points": 0,
      "Number of Questions": 8,
      "Assignment Group": "Project",
      "Shuffle Answers": "No",
      "Time Limit": "No Limit",
      "Multiple Attempts": "Yes",
      "How Many Attempts": 5,
      "Show Correct Answers": "Always",
      "Access Code": "",
      "One Question at a Time": "No",
      "Webcam Required": "No",
      "Lock Questions After Answering": "No",
      "Due Date": "2025-04-25",
      "Available Date": "2025-04-20",
      "Until Date": "2025-04-26"
    },
    {
      "Quiz Type": "Graded Quiz",
      "Points": 100,
      "Number of Questions": 20,
      "Assignment Group": "Exams",
      "Shuffle Answers": "Yes",
      "Time Limit": "45 Minutes",
      "Multiple Attempts": "No",
      "How Many Attempts": 1,
      "Show Correct Answers": "After Until Date",
      "Access Code": "FINAL2025",
      "One Question at a Time": "Yes",
      "Webcam Required": "Yes",
      "Lock Questions After Answering": "Yes",
      "Due Date": "2025-05-05",
      "Available Date": "2025-05-01",
      "Until Date": "2025-05-06"
    }
  ]
